sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t jvalluri5/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jvalluri5/docker-react npm run test