version: '3'
services:
    webapp:
        build:
            context: .
            dockerfile: Dockerfile.dev
        stdin_open: true
        volumes:
            - /usr/app/node_modules
            - .:/usr/app
        ports:
            - "3000:3000"
        